#!/usr/bin/env bash
#a Bash script that transfers
#a file from our client to a server

if [ "$#" -lt 4 ]; then
        echo "Usage: $0 TATH_TO_FILE IP USERNAME
        PATH_TO_SSH_KEY"
        exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh=$4

scp StrictHostKeyChecking=no -i "$path_to_ssh" "$path_to_file" "$username"@"$ip":~/ || { echo "File transfer failed"; exit 1; }

echo "File transferred successfully to $username@$ip:~/"
