#!/usr/bin/env bash
#a Bash script that configures a new Ubuntu machine

sudo apt update

sudo apt install -y nginx

sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf

echo "<!DOCTYPE html>
<html>
<head>
  <title>Hello World!</title>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>" | sudo tee /var/www/html/index.html > /dev/null 

sudo service nginx restart

ps -ef | grep nginx | grep -v grep > /dev/null
