#!/usr/bin/env bash
# duplicate web-01 to web-02

echo -e "Updating...\n"

function install() {
	if ! command -v "$1" &> /dev/null; then
                echo -e "       Installing: $1$\n"
                sudo apt-get update -y -qq && \
                        sudo apt-get install -y "$1" -qq
                echo -e "\n"
        else
                echo -e "       ${1} is already installed.\n"
        fi
}

install nginx #install nginx

echo -e "\nSetting up.\n"

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html /var/www/error

sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/error_404.html

sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
                listen 80 default_server;
                listen [::]:80 default_server;
                root /var/www/html;
                index index.html index.htm index.nginx-debian.html
                server_name_;
                add_header X-Served-By \$hostname;
                location / {
                        try_files \$uri \$uri/ =404;
                }
                if (\$request_filename ~ redirect_me){
                        rewrite ^ https://th3-gr00t.tk/ permanent;
                }
                error_page 404 /error_404.html;
                location = /error_404.html {
                        internal;
                }
}"

echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
