#!/usr/bin/env bash
# a bash code that fix the probleme when Nginx isn't listening on port 80

if ! grep -q "listen 80 default_server;" /etc/nginx/sites-enabled/default; then
	echo "Error: 'listen 80 default_server;' is missing or misconfigured in /etc/nginx/sites-enabled/default"
	# Find and replace the line to bind port 80 to all IPv4 addresses in the default site configuration file
	echo "Updating the configuration to bind port 80 to all IPv4 addresses..."
	awk '/^server {/,/^listen \[::\]:80 default_server;/ { if ($0 ~ /^ *listen [[:digit:]]+ default_server;/) print "        listen 80 default_server;"; else print; next } 1' /etc/nginx/sites-enabled/default > /tmp/default.tmp && mv /tmp/default.tmp /etc/nginx/sites-enabled/default
fi

# Restart Nginx to apply the configuration changes
echo "Restarting Nginx..."
sudo systemctl restart nginx

echo "Nginx configuration updated successfully."
