#!/usr/bin/env bash
#a bash script that run the whoami command

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

# Get the username from the argument
USERNAME=$1

# Run the whoami command as the specified user
sudo -u "$USERNAME" whoami
