#!/usr/bin/env bash
#configure nginx to be running as nginx user

sudo service nginx stop

sudo sed -i "s/#user www.data;/user nginx;/" /etc/nginx/nginx.conf

sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default

sudo chmod 644 /etc/nginx/nginx.conf

sudo chown -R nginx:nginx /etc/nginx/

for pid in $(pidof apache2); do
	sudo kill "$pid"
done

sudo service nginx start
