#!/usr/bin/env bash

# Stop NGINX service
sudo service nginx stop

# Update NGINX configuration to run as nginx user
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Change the default listen port from 80 to 8080
sudo sed -i "s/listen 80;/listen 8080;/" /etc/nginx/sites-enabled/default

# Set correct permissions for the NGINX configuration file
sudo chmod 644 /etc/nginx/nginx.conf

# Change ownership of the NGINX directory to nginx user and group
sudo chown -R nginx:nginx /etc/nginx/

# Stop Apache2 if it's running
for pid in $(pidof apache2); do
	sudo kill "$pid"
done

# Start NGINX service as the nginx user
sudo -u nginx service nginx start
