#!/usr/bin/env bash

sudo service nginx stop
sudo sed -i 's/#user www-data;/user nginx;/; s/listen 80;/listen 8080;/' /etc/nginx/nginx.conf /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf && sudo chown -R nginx:nginx /etc/nginx/
pidof apache2 | xargs -r sudo kill && sudo service nginx start
